# Ansible inventory generated by Terraform

[servers]
${vm_name} ansible_host=${external_ip} ansible_user=${ssh_user}

[servers:vars]
internal_ip=${internal_ip}
external_ip=${external_ip}
domain=${domain}

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_pipelining=true